SELECT U.USER_ID USER_ID, U.NICKNAME NICKNAME,SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS LIKE "%DONE%"
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3
